spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.api-key=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
spring.ai.retry.max-attempts=3
spring.datasource.url=jdbc:mysql://localhost:3306/health
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=kjhgeuuuhdfsdbnnjahyutwtyiiolkhuygvbbjdjkdkdkdduidyyytt