spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.api-key=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
spring.datasource.url=jdbc:mysql://localhost:3306/health
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=kjhgeuuuhdfsdbnnjahyutwtyiiolkhuygvbbjdjkdkdkdduidyyytt